---

- name: Setup Docker registry
  hosts: docker_registry
  become: yes
  become_method: sudo
  gather_facts: no

  pre_tasks:
    - import_role:
        name: common
        tasks_from: docker-image-prune
      tags:
        - always

  tasks:
    - import_role:
        name: docker-registry
        tasks_from: install-cache
      tags:
        - cache

    - import_role:
        name: docker-registry
        tasks_from: install-registry
      tags:
        - base

    - import_role:
        name: docker-registry
        tasks_from: install-auth
      tags:
        - auth

    - import_role:
        name: docker-registry
        tasks_from: install-web
      tags:
        - web

  post_tasks:
    - import_role:
        name: common
        tasks_from: container-status-check
      tags:
        - always
      vars:
        container_names:
          - "{{ registry_container_name }}"
          - "{{ registry_auth_container_name }}"
          - "{{ registry_cache_container_name }}"
          - "{{ registry_web_container_name }}"



