---

- name: Setup vsftp
  hosts: ftp
  become: yes
  become_method: sudo
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  gather_facts: no

  pre_tasks:
    - import_role:
        name: common
        tasks_from: sync-time
      tags:
        - always

    - import_role:
        name: common
        tasks_from: apt-update
      tags:
        - always

  tasks:
    - import_role:
        name: vsftp
      tags:
        - install

# POST TASK - test status of the service!
