---

# https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html

all:
  # Ungrouped hosts
  hosts:
    ftp:

  children:
    # Define groups

    docker_group:
      hosts:
        docker_cloud:
        docker_registry:
        jenkins:

