---

- name: Ensure Docker registry auth image is present
  docker_image:
    name: "{{ registry_auth_image_name }}:{{ registry_auth_image_tag }}"
    force_source: yes
    source: pull
    state: present

- name: Ensure {{ registry_config_dir }} folder is present on {{ prefix }} registry host
  file:
    path: "{{ registry_config_dir }}"
    state: directory

- name: Ensure Docker registry auth configuration file is present on {{ prefix }} registry host
  template:
    src: auth/config.yml.j2
    dest: "{{ registry_config_dir }}/config-registry-auth.yml"
  notify: "Restart Docker registry auth service"

- name: Ensure Docker registry auth service configuration file is present on {{ prefix }} registry host
  template:
    src: auth/service.j2
    dest: /lib/systemd/system/docker-registry-auth.service
  notify: "Restart Docker registry auth service"
