---

- name: Ensure Docker registry cache image is present
  docker_image:
    name: "{{ registry_cache_image_name }}:{{ registry_cache_image_tag }}"
    force_source: yes
    source: pull
    state: present

- name: Ensure Docker registry cache configuration directory is present
  file:
    path: "{{ cache_config_dir }}"
    state: directory

- name: Ensure Docker registry cache data directory is present
  file:
    path: "{{ cache_data_dir }}"
    state: directory

- name: Ensure Docker registry cache configuration is present
  template:
    src: cache/config.yml.j2
    dest: "{{ cache_config_dir }}/config.yml"
  notify: "Restart Docker registry cache service"

- name: Ensure Docker registry cache configuration env file is present
  template:
    src: cache/env.file.j2
    dest: "{{ cache_config_dir }}/env.file"
  notify: "Restart Docker registry cache service"

- name: Ensure Docker registry cache service configuration is present
  template:
    src: cache/service.j2
    dest: /lib/systemd/system/docker-registry-cache.service
  notify: "Restart Docker registry cache service"

