---

- name: Ensure Docker registry web image is present
  docker_image:
    name: "{{ registry_web_image_name }}:{{ registry_web_image_tag }}"
    force_source: yes
    source: pull
    state: present

- name: Ensure {{ registry_config_dir }} folder is present on {{ prefix }} registry host
  file:
    path: "{{ registry_config_dir }}"
    state: directory

- name: Ensure {{ registry_config_dir }} folder is present on {{ prefix }} registry host
  file:
    path: "{{ registry_web_dir }}"
    state: directory

- name: Ensure Docker registry web configuration file is present on {{ prefix }} registry host
  template:
    src: web/config.yml.j2
    dest: "{{ registry_config_dir }}/config-registry-web.yml"
  notify: "Restart Docker registry web service"

- name: Ensure Docker registry web service configuration file is present on {{ prefix }} registry host
  template:
    src: web/service.j2
    dest: /lib/systemd/system/docker-registry-web.service
  notify: "Restart Docker registry web service"
