- name: Ensure {{ jenkins_cs_prefix }} builder Docker network is present
  docker_network:
    name: "{{ jenkins_cs_builder_network_name }}"
    driver: bridge
    scope: local
    attachable: yes
    labels:
      jenkins.instance: "{{ jenkins_cs_prefix }}"
      jenkins.url: "{{ jenkins_dns }}"

- name: Ensure stash key folder is present on {{ jenkins_cs_prefix }} Docker cloud host
  file:
    path: "/home/{{ docker_user }}/stash_key"
    state: directory

- name: Ensure {{ jenkins_cs_prefix }} Jenkins CS stash key is present on host
  copy:
    content: "{{ jenkins_stash_private_key }}"
    dest: "{{ docker_user_home }}/stash_key/id_rsa"

- name: Ensure {{ jenkins_cs_prefix }} builder stash key volume is present on host
  docker_volume:
    name: "{{ jenkins_cs_builder_volume_name }}"
    labels:
      jenkins.instance: "{{ jenkins_cs_prefix }}"
      jenkins.url: "{{ jenkins_dns }}"
      purpose: "stash key"
    state: present

- name: Log into {{ prefix }} registry
  docker_login:
    registry: "{{ hostvars.docker_registry.ansible_host }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"

- name: Ensure {{ jenkins_cs_prefix }} stash key distribution container is created
  docker_container:
    name: keycopy
    image: "{{ docker_cloud_build_images.busybox.new_tag }}"
    volumes:
      - "{{ jenkins_cs_builder_volume_name }}:/mnt/dst"
    state: present

- name: Ensure {{ jenkins_cs_prefix }} Stash private key is copied into volume
  shell: "docker cp {{ docker_user_home }}/stash_key/id_rsa keycopy:/mnt/dst/id_rsa"

- name: Ensure {{ jenkins_cs_prefix }} stash key distribution container is removed
  docker_container:
    name: keycopy
    state: absent