- name: Ensure {{ prefix }} Nginx configuration directory is present
  file:
    path: "{{ nginx_file_path }}"
    state: directory

- name: Ensure {{ prefix }} Nginx Docker Compose file is present
  template:
    src: jenkins-nginx/docker-compose.yml.j2
    dest: "{{ nginx_file_path }}/docker-compose.yml"

- name: Ensure {{ prefix }} Nginx configuration file is present
  template:
    src: jenkins-nginx/nginx.conf.j2
    dest: "{{ nginx_file_path }}/nginx.conf"

- name: Log into {{ registry_host }}
  docker_login:
    registry: "{{ registry_host }}"
    username: "{{ registry_credentials.username }}"
    password: "{{ registry_credentials.password }}"

- name: Ensure {{ prefix }} Nginx service is running
  docker_compose:
    project_name: "{{ nginx_prefix }}"
    project_src: "{{ nginx_file_path }}"
    remove_images: all
    pull: yes
    recreate: always
    # TEMP
    remove_volumes: yes
    state: present
