- name: Ensure Docker daemon configuration file is present
  template:
    src: jenkins/daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: "Restart Docker"

- name: Ensure Docker certificate directory for production registry is present
  file:
    path: "/etc/docker/certs.d/{{ registry_host }}"
    state: directory
    recurse: yes

- name: Ensure production Docker registry client certificate is present
  copy:
    content: "{{ registry_ca }}"
    dest: "/etc/docker/certs.d/{{ registry_host }}/ca.crt"
  no_log: true
  notify: "Restart Docker"
