- name: Install Docker
  hosts: all
  become: yes
  become_method: sudo
  pre_tasks:
    - import_role:
        name: common
        tasks_from: sync
      tags:
        - always

  tasks:
    - import_role:
        name: docker

  post_tasks:
    - import_role:
        name: common
        tasks_from: service-status-check
      tags:
        - always
      vars:
        service_names:
          - "docker"
