---

- name: Ensure Docker daemon configuration file is present for {{ prefix }} registry
  template:
    src: docker-registry/daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: "Restart Docker"

- name: Ensure Docker service Drop-In directory is present for {{ prefix }} registry services
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Ensure Docker proxy configuration file is present for {{ prefix }} registry cache
  template:
    src: docker-registry/proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/proxy.conf
  notify: "Restart Docker"
