---

# https://docs.docker.com/install/linux/docker-ce/ubuntu/

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools

- name: Ensure apt signing key for Docker is present
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Ensure apt repository for stable version is present
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable

- name: Ensure Docker packages are present
  apt:
    name: "{{ packages }}"
    state: present
    purge: true
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify: "Restart Docker"

- name: Ensure Docker Python modules are present
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: Ensure Docker user is present
  user:
    name: "{{ docker_user }}"
    group: docker
    remove: yes
    shell: "/bin/bash"
    state: present

- name: Ensure CI team member public keys are present
  authorized_key:
    user: "{{ docker_user }}"
    state: present
    key: "{{ item }}"
  no_log: true
  with_file:
    - files/authorized_keys

