---

# When accessing the ansible_facts.services facts collected by this module, it is recommended to not use “dot notation” because services can have a - character in their name which would result in invalid “dot notation”, such as ansible_facts.services.zuul-gateway. It is instead recommended to using the string value of the service name as the key in order to obtain the fact data value like ansible_facts.services['zuul-gateway']

- name: Populate service facts
  service_facts:
  no_log: true

- name: Assert that service is up and running
  assert:
    quiet: yes
    that:
      - "'running' in ansible_facts.services['{{ item }}']['state']"
    success_msg: "{{ item }} service is running!"
    fail_msg : "{{ item }} service is NOT running!"
  loop: "{{ service_names|flatten(levels=1) }}"
