---

# Docker registry
registry_image_name: registry
registry_image_tag: 2
registry_container_name: "{{ prefix }}-registry"
registry_config_dir: /etc/docker-registry
registry_data_dir: /var/lib/registry
registry_web_dir: /var/lib/registry_web

# Docker registry auth
registry_auth_image_name: cesanta/docker_auth
registry_auth_image_tag: latest
registry_auth_container_name: "{{ prefix }}-registry-auth"

# Docker registry cache
registry_cache_image_name: registry
registry_cache_image_tag: 2
registry_cache_container_name: "{{ prefix }}-registry-cache"
cache_config_dir: /etc/docker-cache
cache_data_dir: /var/lib/docker-cache

# Docker registry web
registry_web_image_name: hyper/docker-registry-web
registry_web_image_tag: latest
registry_web_container_name: "{{ prefix }}-registry-web"



