---

# Install vsftpd packages

- name: vsftpd packages are installed
  package:
    name: vsftpd
    state: present

- name: Ensure group "exchange" exists
  group:
    name: exchange
    state: present

- name: Add the user 'exchange' with a primary group of 'exchange'
  user:
    name: exchange
    password: "{{ ftp_encrypted_exchange_password }}"
    home: "{{ ftp_home_dir }}"
    shell: "/bin/false"
    comment: FTP exchange user
    group: exchange

- name: add '/bin/false' to /etc/shells
  lineinfile:
    dest=/etc/shells
    line="/bin/false"
    state=present

- name: Ensure directory {{ ftp_home_dir }} exists
  file:
    path: "{{ ftp_home_dir }}"
    mode: a-w

- name: Ensure directory public exists
  file:
    path: "{{ ftp_home_dir }}/public/dists"
    owner: exchange
    group: exchange
    state: directory
    mode: 0775

- name: Ensure directory exchange exists
  file:
    path: "{{ ftp_home_dir }}/exchange"
    owner: exchange
    group: exchange
    state: directory
    mode: 0777

# Configure vsftpd

- name: Ensures vsftpd.conf is present
  template:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  notify: Restart vsftpd service

- name: vsftpd service is enabled and started
  service:
    name: vsftpd
    enabled: true
    state: started
